services:
- type: web
  name: sales-bot-admin
  env: node
  buildCommand: npm run build
  startCommand: npm start
  envVars:
  - key: NODE_ENV
    value: production
  - key: DATABASE_URL
    sync: false
  - key: TELEGRAM_BOT_TOKEN
    sync: false
  - key: GEMINI_API_KEY
    sync: false